# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_auto_20161020_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default='Anonymous troll', max_length=45),
            preserve_default=False,
        ),
    ]
